# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02Validarsaludoausuraio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02Validarsaludoausuraio(self):
    self.driver.get("https://demo.testim.io/")
    self.driver.find_element(By.CSS_SELECTOR, ".NavButton__nav-button___34wHC").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Login__field___2oefU:nth-child(1) > .theme__inputElement___27dyY").send_keys("Joese ")
    self.driver.find_element(By.CSS_SELECTOR, ".Login__field___2oefU:nth-child(2) > .theme__inputElement___27dyY").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Login__field___2oefU:nth-child(2) > .theme__inputElement___27dyY").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".LoginButton__raised___1fUxJ").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".mui-btn > span:nth-child(1)").text == "HOLA,Joese"
  
